### ISSUE TITLE
NullPointerException for invalid ttl file

### ISSUE THREAD

**Issue by JJ-Author** [imas/setup-rdflint#5]
Hi, maybe I am still confused what this linter is supposed to do, but I thought it would show me errors in ttl files. I just inserted an invalid ttl file to test and as a result I get a NullPointerException and there seems no way to actually find the incorrect ttl file in the log. 

https://github.com/dbpedia/format-mappings/runs/554543342?check_suite_focus=true

```
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:91)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:41)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:191)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:352)
	at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:321)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:295)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:237)
	at com.github.imas.rdflint.validator.impl.RdfSyntaxValidator.validateFile(RdfSyntaxValidator.java:65)
	at com.github.imas.rdflint.ValidationRunner.lambda$null$4(ValidationRunner.java:77)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.imas.rdflint.ValidationRunner.lambda$execute$5(ValidationRunner.java:77)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.github.imas.rdflint.ValidationRunner.execute(ValidationRunner.java:77)
	at com.github.imas.rdflint.RdfLint.lintRdfDataSet(RdfLint.java:223)
	at com.github.imas.rdflint.RdfLint.main(RdfLint.java:140)
##[error]Process completed with exit code 1.
```

**Comment by foooomio** [comment]
Hi, thanks for reporting, but this is also the issue with rdflint, not setup-rdflint.

Please run rdflint in your local environment and confirm if the same error occurs. If there is a different behavior, the problem is with setup-rdflint.

Transfering to imas/rdflint.
